### ISSUE TITLE
How to execute other sampling methods in papers such as BPR?

### ISSUE THREAD

**Issue by datacheff** [swt-user/WWW_2023_code#1]
Hello, thanks for the interesting research.
How to execute other sampling methods in papers such as BPR?
What are the arguments for BPR?

Thank you.

**Comment by swt-user** [comment]
Thanks for your interest.
`python main_more.py --sampler 0 --fix_seed `  For BPR
 You can refer to [AdaSIR](https://github.com/HERECJ/AdaSIR) for more details about other baselines.

**Comment by datacheff** [comment]
Thank you! 
The research is really impressive. thanks for the good research
